language: go

dist: focal
sudo: required

go: "1.16.14"

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      virt: vm
      group: edge
    - arch: amd64
      name: "amd64-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:2a85888a4c8db02b36de0939161910cae48cd74c@sha256:11bf7e098eb715b13e1f09a1743fe557973a30df95528dce568e1c509df8d7be
        - LOCKDEBUG=1
    - arch: arm64-graviton2
      name: "arm64-graviton2-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:2a85888a4c8db02b36de0939161910cae48cd74c@sha256:11bf7e098eb715b13e1f09a1743fe557973a30df95528dce568e1c509df8d7be
        - LOCKDEBUG=1
      virt: vm
      group: edge

if: branch = master OR type = pull_request

addons:
  apt:
    packages:
      - kernel-package
      - gnupg
      - libelf-dev
      - libncurses5

before_install: ./.travis/prepare.sh

before_script:
  - export PATH=/usr/local/clang/bin:$PATH

script: ./.travis/build.sh

notifications:
  email: false
